AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-asana-lambda

    Get account info from Asana

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    AsanaWhoamiFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: asana/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                AsanaWhoami:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /whoami
                        Method: get

Outputs:

    AsanaWhoamiApi:
      Description: "API Gateway endpoint URL for Prod stage for Asana Whoami function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/whoami/"

    AsanaWhoamiFunction:
      Description: "Asana Whoami Lambda Function ARN"
      Value: !GetAtt AsanaWhoamiFunction.Arn

    AsanaWhoamiFunctionIamRole:
      Description: "Implicit IAM Role created for Asana Whoami function"
      Value: !GetAtt AsanaWhoamiFunctionRole.Arn
